axis_threshold: 0.5
use_ctrl_space_for_kanji_key: true
long_press_threshold_sec: 0.2
software_key_repeat_enabled: true
software_key_repeat_delay_sec_first: 0.3
software_key_repeat_delay_sec: 0.06
# jp_input_mode: FLICK
jp_input_mode: ROMAJI
pyautogui_pause_sec: 0.03
flick_dakuten_double_backspace: false
flick_axis_threshold: 0.3
mouse_axis_threshold: 0.3
mouse_move_speed_normal: 4
mouse_move_speed_slow: 2
mouse_move_speed_fast: 8
mouse_move_speed_very_slow: 1